Repository wecode-bootcamp-korea/49-3rd-DKDK-backend, pull requests merged in 2023-10, with the labels that each got.

#4 feat: dbmate 설정
  .gitignore
  db/migrations/20231013060706_create_users_table.sql
  db/migrations/20231013060927_create_tables_trainers.sql
  db/migrations/20231013061848_create_tables_subscriptions.sql
  db/migrations/20231013062009_create_tables_sub_orders.sql
  db/migrations/20231013062044_create_tables_pt_orders.sql
  db/migrations/20231013062216_create_table_products.sql
  db/migrations/20231013062415_create_table_workout_categories.sql
  db/migrations/20231013062459_create_table_workouts.sql
  db/migrations/20231013062749_create_table_meal_plans.sql
  db/migrations/20231013085144_create_table_food_types.sql
  db/migrations/20231013085225_create_table_foods.sql
  db/migrations/20231013085334_create_table_workout_records.sql
  db/migrations/20231013085412_create_table_posts.sql
  db/migrations/20231013085521_create_table_comments.sql
  db/migrations/20231013085624_create_table_likes.sql
Labels: 멘토 리뷰 요청

#11 hotfix : not_null 수정했습니다
  db/migrations/20231018140931_alter_user_data.sql
  db/schema.sql
Labels: 멘토 리뷰 요청

#10 Feature/login
  app.js
  db/migrations/20231016074624_alter_decimal_data.sql
  db/schema.sql
  package-lock.json
  package.json
  server.js
  src/config/passport.js
  src/controllers/authController.js
  src/controllers/index.js
  src/controllers/userController.js
  src/middlewares/auth.js
  src/models/index.js
  src/models/userDao.js
  src/routes/authRoute.js
  src/routes/index.js
  src/routes/userRoute.js
  src/services/index.js
  src/services/userService.js
  src/utils/generateToken.js
  tests/auth.test.js
  tests/user.test.js
Labels: 멘토 리뷰 요청

#18 fix: Feature/middleware fix
  app.js
  package-lock.json
  src/utils/keyError.js
Labels: 멘토 리뷰 요청

#9 Feature/records
  .gitignore
  src/controllers/index.js
  src/controllers/recordController.js
  src/models/dataSource.js
  src/models/index.js
  src/models/recordDao.js
  src/routes/index.js
  src/routes/recordRouter.js
  src/services/index.js
  src/services/recordService.js
  tests/record.test.js
Labels: 수정 요청

#24 Feature/subscription
  env.test
  package-lock.json
  package.json
  src/controllers/index.js
  src/controllers/subscriptionController.js
  src/models/index.js
  src/models/subscripntionDao.js
  src/models/userDao.js
  src/routes/index.js
  src/routes/subscriptionRoute.js
  src/services/index.js
  src/services/subscriptionService.js
  tests/subscription.test.js
Labels: 멘토 리뷰 요청

#17 Feature/trainermatching
  db/schema.sql
  package-lock.json
  src/controllers/index.js
  src/controllers/trainerMatchingController.js
  src/models/dataSource.js
  src/models/index.js
  src/models/trainerMatchingDao.js
  src/models/trainerQueryBuilder.js
  src/routes/index.js
  src/routes/trainerMatchingRoute.js
  src/services/index.js
  src/services/trainerMatchingService.js
  src/services/userService.js
  tests/trainerMatching.test.js
Labels: 멘토 리뷰 요청, 수정 요청

#19 Feature/mypage post
  env.test
  package-lock.json
  package.json
  src/controllers/userHealthInfoController.js
  src/middlewares/auth.js
  src/models/userHealthInfoDao.js
  src/routes/userHealthInfoRouter.js
  src/services/userHealthInfoService.js
  src/utils/S3.js
  src/utils/s3Service.js
  tests/test-image.jpg
  tests/userHealthInfo.test.js
Labels: 멘토 리뷰 요청, 수정 요청
